name: build I-TTS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Apps/Discord/I-TTS/**'
jobs:
  push:
    name: "yolks:i-tts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Apps/Discord/I-TTS
          file: ./Apps/Discord/I-TTS/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:i-tts