name: build MariaDB
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'DB/MariaDB/MariaDB-10.6/**'
      - 'DB/MariaDB/MariaDB-10.11/**'
      - 'DB/MariaDB/MariaDB-11.4/**'
      - 'DB/MariaDB/MariaDB-11.8/**'
      - 'DB/MariaDB/MariaDB-12.1/**'
jobs:
  push:
    name: "yolks:mariadb-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '10.6'
          - '10.11'
          - '11.4'
          - '11.8'
          - '12.1'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./DB/MariaDB/MariaDB-${{ matrix.tag }}
          file: ./DB/MariaDB/MariaDB-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:mariadb-${{ matrix.tag }}