name: build Amazon-Corretto-JP
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-8_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-11_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-16_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-17_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-18_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-19_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-20_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-21_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-22_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-23_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-24_JP/**'
      - 'Java/Amazon-Corretto-JP/Amazon-Corretto-25_JP/**'
jobs:
  push:
    name: "yolks:amazon-corretto-${{ matrix.tag }}_jp"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Java/Amazon-Corretto-JP/Amazon-Corretto-${{ matrix.tag }}_JP
          file: ./Java/Amazon-Corretto-JP/Amazon-Corretto-${{ matrix.tag }}_JP/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:amazon-corretto-${{ matrix.tag }}_jp