name: build Amazon-Corretto
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Java/Amazon-Corretto/Amazon-Corretto-8/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-11/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-16/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-17/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-18/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-19/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-20/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-21/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-22/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-23/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-24/**'
      - 'Java/Amazon-Corretto/Amazon-Corretto-25/**'
jobs:
  push:
    name: "yolks:amazon-corretto-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Java/Amazon-Corretto/Amazon-Corretto-${{ matrix.tag }}
          file: ./Java/Amazon-Corretto/Amazon-Corretto-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:amazon-corretto-${{ matrix.tag }}